"use client";

interface AIInsight {
  type: 'networking' | 'growth' | 'strategy' | 'opportunities';
  title: string;
  content: string;
  confidence: number;
}

interface AIInsightsProps {
  insights: AIInsight[];
  userTier: 'pro' | 'enterprise';
}

const getInsightIcon = (type: string) => {
  switch (type) {
    case 'networking': return '🤝';
    case 'growth': return '📈';
    case 'strategy': return '🎯';
    case 'opportunities': return '💡';
    default: return '✨';
  }
};

const getConfidenceColor = (confidence: number) => {
  if (confidence >= 0.8) return '#10b981'; // green
  if (confidence >= 0.6) return '#f59e0b'; // yellow
  return '#6b7280'; // gray
};

export default function AIInsights({ insights, userTier }: AIInsightsProps) {
  if (!insights || insights.length === 0) {
    return (
      <div style={{ background: "white", padding: "2rem", borderRadius: "8px", marginBottom: "2rem" }}>
        <h2 style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "1rem" }}>
          ✨ AI-Powered Insights
        </h2>
        <p style={{ color: "#6b7280" }}>
          AI insights are being generated. This may take a few moments for complex network analysis.
        </p>
      </div>
    );
  }

  return (
    <div style={{ background: "white", padding: "2rem", borderRadius: "8px", marginBottom: "2rem" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem" }}>
        <h2 style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          ✨ AI-Powered Insights
        </h2>
        <span style={{ 
          background: userTier === 'enterprise' ? '#7c3aed' : '#3b82f6', 
          color: 'white', 
          padding: '0.25rem 0.75rem', 
          borderRadius: '12px', 
          fontSize: '0.75rem',
          textTransform: 'uppercase',
          fontWeight: 'bold'
        }}>
          {userTier}
        </span>
      </div>
      
      <div style={{ display: "grid", gap: "1.5rem" }}>
        {insights.map((insight, index) => (
          <div 
            key={index} 
            style={{ 
              border: "1px solid #e5e7eb", 
              borderRadius: "8px", 
              padding: "1.5rem",
              background: "#fafafa"
            }}
          >
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "1rem" }}>
              <h3 style={{ 
                display: "flex", 
                alignItems: "center", 
                gap: "0.5rem", 
                fontSize: "1.125rem", 
                fontWeight: "bold",
                margin: 0
              }}>
                <span style={{ fontSize: "1.5rem" }}>{getInsightIcon(insight.type)}</span>
                {insight.title}
              </h3>
              <div style={{ 
                display: "flex", 
                alignItems: "center", 
                gap: "0.25rem",
                fontSize: "0.75rem",
                color: getConfidenceColor(insight.confidence)
              }}>
                <span style={{ 
                  width: "8px", 
                  height: "8px", 
                  borderRadius: "50%", 
                  background: getConfidenceColor(insight.confidence) 
                }} />
                {Math.round(insight.confidence * 100)}% confidence
              </div>
            </div>
            
            <p style={{ 
              color: "#374151", 
              lineHeight: "1.6", 
              margin: 0,
              fontSize: "0.95rem"
            }}>
              {insight.content}
            </p>
            
            <div style={{ 
              marginTop: "1rem", 
              padding: "0.5rem", 
              background: "#f0f9ff", 
              borderRadius: "4px",
              fontSize: "0.75rem",
              color: "#0369a1"
            }}>
              💡 This insight was generated by AI analysis of your LinkedIn network data
            </div>
          </div>
        ))}
      </div>
      
      {userTier === 'pro' && (
        <div style={{ 
          marginTop: "2rem", 
          padding: "1rem", 
          background: "#fefce8", 
          border: "1px solid #fde047",
          borderRadius: "4px",
          fontSize: "0.875rem"
        }}>
          <strong>Upgrade to Enterprise</strong> for custom AI analysis prompts and advanced strategic insights.
        </div>
      )}
    </div>
  );
}
